[config]
skip_core_tasks = true

[tasks.format]
description = "cargo fmt"
category = "Development"
script_runner = "@shell"
script = '''
cd crates/${@} && cargo fmt
'''

[tasks.check]
description = "cargo check"
category = "Test"
script_runner = "@shell"
script = '''
cd crates/${@} && cargo check
'''
dependencies = ["format"]

[tasks.build]
description = "cargo build"
category = "Build"
script_runner = "@shell"
script = '''
cd crates/${@} && cargo build
'''
dependencies = ["check"]

[tasks.run]
description = "cargo run"
category = "Build"
script_runner = "@shell"
script = '''
cd crates/${@} && cargo run
'''
dependencies = ["build"]

[tasks.clippy]
description = "cargo clippy"
category = "Test"
script_runner = "@shell"
script = '''
cd crates/${@} && cargo clippy
'''
dependencies = ["check"]

[tasks.test]
description = "cargo nextest"
category = "Test"
install_crate = { crate_name = "cargo-nextest", binary = "cargo", test_arg = ["nextest", "--help"] }
script_runner = "@shell"
script = '''
cd crates/${@} && cargo nextest run
'''
dependencies = ["clippy"]

[tasks.coverage]
description = "cargo llvm-cov"
category = "Test"
install_crate = { crate_name = "cargo-llvm-cov", binary = "cargo", test_arg = ["llvm-cov", "--help"] }
script_runner = "@shell"
script = '''
cd crates/${@} && cargo llvm-cov
'''
dependencies = ["test"]

[tasks.coverage-html]
description = "cargo llvm-cov --html"
category = "Test"
install_crate = { crate_name = "cargo-llvm-cov", binary = "cargo", test_arg = ["llvm-cov", "--help"] }
script_runner = "@shell"
script = '''
cd crates/${@} && cargo llvm-cov --html
'''
dependencies = ["test"]

[tasks.coverage-open]
description = "open coverage report"
category = "Test"
script_runner = "@shell"
script = '''
cd crates/${@} && cargo llvm-cov --open
'''
dependencies = ["test"]

[tasks.clean]
description = "cargo clean"
category = "Development"
script_runner = "@shell"
script = '''
cd crates/${@} && cargo clean
'''
